Implement contacting whole group (issue 9)
DataManagementLab/bp-tool pull request #21
Opened 2022-07-05 08:25 UTC by Jonas-July

The model Project now exposes the students email for use in the view and its template.

The change in the template is basically a copy of the line for the AG contact functionality that already existed.

2022-07-05 17:38 UTC, bhaettasch commented
Zumindest mit meinem Mail-Client funktioniert die Komma-separierte Liste von Mailadressen leider nicht, siehe auch hier: https://stackoverflow.com/questions/13765286/send-mail-to-multiple-receiver-with-html-mailto

Vermutlich wäre es sinnvoll, mindestens auf der Detailseite zunächst alle Adressen individuell zu verlinken, sodass man die zumindest leicht kopieren kann und zusätzlich dann noch einen Mai-An-Alle-Button einzufügen, der vielleicht bei manchen Clients funktioniert.

2022-07-05 17:39 UTC, bhaettasch requested changes

2022-07-05 17:39 UTC, bhaettasch commented on bp/templates/bp/project.html
> +            <td>Mitglieder:</td><td><a href="mailto:{{ project.student_mail }}">{{ project.student_list }}&nbsp;{% fa5_icon "envelope" "far" %}</a></td>
Siehe Kommentar

2022-07-06 14:27 UTC, Jonas-July commented
Gut, wie ich es mit meinem Client (thunderbird) probiert hab, hat es geklappt, daher hab ich nicht weiter geschaut.
Die Emails unter den Mitgliedern anzuzeigen sollte möglich sein

2022-07-06 14:48 UTC, Jonas-July commented
Auf jeder Projektseite werden jetzt die zugehörigen Email-Adressen als schlichter Text angezeigt.
Die Adressen können dann einfach markiert und manuell in den Client eingefügt werden

Ansonsten beschreib bitte genauer, was "Adressen individuell zu verlinken" meint, da sehe ich im Moment nicht, wie das einfacher wäre

2022-07-17 10:40 UTC, bhaettasch approved these changes

2022-07-17 10:40 UTC, bhaettasch commented
Sieht gut aus.

2022-07-17 10:40 UTC, merged