5 Enable grading at specified time and send emails after deadline
DataManagementLab/bp-tool pull request #27
Opened 2022-07-15 11:10 UTC by Jonas-July

The beginning and end of the grading phase is specified at the BP level for all projects.

After the beginning, AGs can enter grades as many times as they want. All grading activities are logged. \
After the deadline, AGs can still enter grades, but emails are sent to both the AG and the Orga team.

The valid grade is always the most recent one, whether or not the deadline has passed.

Email should work, though I didn't set up a server myself.

2022-07-15 13:09 UTC, Jonas-July commented
There are still some improvements to be had, but they aren't directly concerned with this PR.

See also #28

2022-07-16 06:08 UTC, Jonas-July commented
Refactoring is complete, ready for review. No further changes are planned until review is done.

2022-07-18 10:42 UTC, bhaettasch requested changes
Habe leider noch ein paar Änderungswünsche.

Insbesondere würde ich vorschlagen, die Migrations nochmal neu zu erstellen/zu squashen*, ist ja eigentlich nicht nötig, dass wir Änderungen an Modellen tracken, wenn die zwischendurch niemals deployed waren. Bei der Gelegenheit kann man ihnen dann gleich sprechende Namen geben.

* dazu mittels migrate bp <id_von_der_migration_davor> auf einen alten Stand zurückmigrieren, die Migrations löschen und dann neu erstellen lassen

2022-07-18 10:42 UTC, bhaettasch commented on bp/forms.py
> +            url = f"{'https://' + settings.ALLOWED_HOSTS[0] if len(settings.ALLOWED_HOSTS) > 0 else 'http://localhost'}/admin/bp/aggrade/"#{reverse_lazy('bp:grade_detail', kwargs={'pk': instance.pk})
Den Kommentar vielleicht noch entfernen (oder dokumentieren, warum an der Stelle nicht die reverse-Funktion verwendet wird).

Generell: Fehlt hier nicht noch in irgendeiner Form eine ID?

2022-07-18 10:42 UTC, bhaettasch commented on bp/forms.py
> +                f"""Es wurde eine neue Bewertung für Gruppe {project.nr} eingetragen. Sie erhalten diese E-Mail, da die Deadline zur Bewertung überschritten wurde.
Die AGs kennen meistens die Nummer ihrer Gruppe gar nicht, potenziell hier auch noch einmal den Titel einfügen

2022-07-18 10:42 UTC, bhaettasch commented on bp/migrations/0015_auto_20220714_1435.py
> +            options={'verbose_name': 'TL-Log-Erinnerung', 'verbose_name_plural': 'TL-Log-Erinnerungen'},
Das gehört hier eigentlich nicht rein, oder?

2022-07-18 10:42 UTC, bhaettasch commented on bp/migrations/0016_auto_20220714_1621.py
> +        ('bp', '0015_auto_20220714_1435'),
Wenn möglich in Zukunft mittels -n den Migrations sprechende Namen geben

2022-07-18 10:42 UTC, bhaettasch commented on bp/views.py
> +class AGGradeView(ProjectByOrderIDMixin, CreateView):
Zeigt der View dann trotzdem schon an, falls es eine vorherige Bewertung gab? Wir müssen damit rechnen, dass AGs vergessen, ob sie schon eine Bewertung eingetragen haben, dann wieder über die Mail in ihrem Posteingang stolpern und auf den Link klicken, um das zu überprüfen -- dann sollte die vorhandene Bewertung im Form angezeigt werden oder zumindest obendrüber eine Meldung, dass bereits eine Bewertung (im besten Fall inklusive Punktzahl) vorliegt

2022-07-18 11:43 UTC, Jonas-July commented on bp/views.py
> +class AGGradeView(ProjectByOrderIDMixin, CreateView):
Defaultmäßig wird nichts angezeigt, aber man könnte die Felder ausfüllen, wie es mit der Punktzahl -1 -> "" gemacht wurde.
Sollte dann die letzte gültige oder die letzte getätigte Bewertung angezeigt werden (bzgl. Deadline)?
In diesem Zusammenhang steht auch #28

2022-07-18 11:47 UTC, Jonas-July commented on bp/forms.py
> +            url = f"{'https://' + settings.ALLOWED_HOSTS[0] if len(settings.ALLOWED_HOSTS) > 0 else 'http://localhost'}/admin/bp/aggrade/"#{reverse_lazy('bp:grade_detail', kwargs={'pk': instance.pk})
Die URL muss sowieso geupdated werden, aber der Hintergrund war, dass es keine View zum Ansehen gibt, weshalb es auf die Admin-Seite verweist.
Man kann aber natürlich direkt auf den Eintrag unter /admin/bp/aggradeafterdeadline/{pk}/change/ verlinken.
In diesem Zusammenhang steht auch #28

2022-07-18 11:48 UTC, Jonas-July commented on bp/migrations/0015_auto_20220714_1435.py
> +            options={'verbose_name': 'TL-Log-Erinnerung', 'verbose_name_plural': 'TL-Log-Erinnerungen'},
Das kam anscheinend von Django, ich hab da nichts gemacht, ja.

2022-07-18 12:08 UTC, Jonas-July commented on bp/forms.py
> +            url = f"{'https://' + settings.ALLOWED_HOSTS[0] if len(settings.ALLOWED_HOSTS) > 0 else 'http://localhost'}/admin/bp/aggrade/"#{reverse_lazy('bp:grade_detail', kwargs={'pk': instance.pk})
Gemäß der Diskussion in #28 wird direkt auf die Projektseite verlinkt

2022-07-21 13:44 UTC, Jonas-July commented on bp/views.py
> +class AGGradeView(ProjectByOrderIDMixin, CreateView):
Es wird die letzte getätigte Bewertung eingesetzt, um die AGs nicht zu verwirren. Zusätzlich sind darunter alle bisherigen Bewertungen einsehbar

2022-07-21 13:45 UTC, Jonas-July commented on bp/migrations/0015_auto_20220714_1435.py
> +            options={'verbose_name': 'TL-Log-Erinnerung', 'verbose_name_plural': 'TL-Log-Erinnerungen'},
Wurde aus diesem PR entfernt, muss aber anderweitig gelöst werden

2022-07-22 10:40 UTC, bhaettasch approved these changes

2022-07-22 10:42 UTC, merged